### ISSUE TITLE
Jupyterbook documentation hasn't compiled correctly

### ISSUE THREAD

**Issue by leifdenby** [mllam/weather-model-graphs#24]
I just spotted that the jupyter notebook for the graph archetypes hasn't rendered correctly:

<img width="1624" alt="Screenshot 2024-09-24 at 19 28 07" src="https://github.com/user-attachments/assets/429ddaff-0ae5-47ba-ab20-ff98dc0219ad">

https://mllam.github.io/weather-model-graphs/creating_the_graph.html#the-keisler-2022-single-range-mesh

I'm not exactly sure what has gone wrong here... any ideas @joeloskarsson / @SimonKamuk?

**Comment by joeloskarsson** [comment]
I also noted this, but forgot to look into it further. Good that you made this issue about it. 

I'm really not sure what causes this. I made some small changes to the documentation in #19 , but not in this part of the notebook, so I doubt that those broke this. The error message makes this seem like it's an issue with displaying the plot rather than anything within our code. 

The whole error message ends with `KeyboardInterrupt: `, which is strange in a non-interactive notebook. Could it be some form of timeout, that kills the notebook cause it is taking too long? I just know that this plotting can be quite slow, and maybe a timeout like that could be implemented as a KeyboardInterrupt?

**Comment by leifdenby** [comment]
Turns out it is a timeout: https://github.com/mllam/weather-model-graphs/actions/runs/11009913195/job/30627889701#step:5:39 - I will see if we can make the build process more patient
